name: flutter_app77
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.0.14
  #bottom_navy_bar: ^5.2.0
  #carousel_slider: ^1.3.1
  percent_indicator: ^2.1.1+1
  font_awesome_flutter: ^8.5.0
  intl: ^0.15.8
  toast: ^0.1.5
  shared_preferences: ^0.5.4+6
  worm_indicator: 0.2.1
 # flutter_rave: ^0.0.5
  smooth_star_rating:
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/c1.jpg
    - assets/images/c2.jpg
    - assets/images/c3.jpg
    - assets/images/c4.png
    - assets/images/c5.jpg
    - assets/images/c8.png
    - assets/images/c7.png
    - assets/images/c6.png
    - assets/images/c9.png
    - assets/images/c10.png
    - assets/images/go.png
    - assets/images/come.png
    - assets/images/home.png
    - assets/images/building.png
    - assets/images/handbag.png
    - assets/images/team.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf